### ISSUE TITLE
"getParameterOrder" not available for .Call() for package "zoidtmb"

### ISSUE THREAD

**Issue by invertdna** [nwfsc-cb/zoidtmb#1]
Here's one I don't know enough to troubleshoot... 

Running the example code as follows:
`y <- matrix(c(3.77, 6.63, 2.60, 0.9, 1.44, 0.66, 2.10, 3.57, 1.33),
            nrow = 3, byrow = TRUE
)`

`fit <- fit_zoidTMB(data_matrix = y)
` 
... I get the following error:

`Error in .Call("getParameterOrder", data, parameters, reportenv, control,  : 
  "getParameterOrder" not available for .Call() for package "zoidtmb"`

Might just be a problem w an older setup. Here's what I'm running:
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          2.1                         
year           2022                        
month          06                          
day            23                          
svn rev        82513                       
language       R                           
version.string R version 4.2.1 (2022-06-23)

**Comment by ericward-noaa** [comment]
Can you try installing TMB? 

https://cran.r-project.org/web/packages/TMB/index.html

And then 
```
library(TMB)
runExample(all=TRUE)
```
Curious what compiler your machine has. I've got:
`
using C++ compiler: ‘Apple clang version 12.0.0 (clang-1200.0.26.2)’
using SDK: ‘MacOSX11.0.sdk’
`

**Comment by invertdna** [comment]
Yep, that all runs fine. 

My gcc compiler is:

Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: x86_64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

(But I use several different machines, so I can try this on a different one if need be).

**Comment by ericward-noaa** [comment]
Ok thanks. The main file looked to not be in the /src folder, but I made sure it's there now -- so maybe try again?

**Comment by invertdna** [comment]
Progress! A different error now, but not one that seems to be very serious:

`Order of parameters:`
`[1] "beta_raw"     "log_phi_inv"  "log_zeta_sds" "zeta_raw"    `
`Not matching template order:`
`[1] "log_phi_inv" "beta_raw"   `
`Your parameter list has been re-ordered.`
`(Disable this warning with checkParameterOrder=FALSE)`
`Error in TMB::MakeADFun(data = tmb_data, parameters = tmb_pars, map = tmb_map,  : `
`  Names in map must correspond to parameter names`

**Comment by ericward-noaa** [comment]
Github issue on my end -- sorry about it. Files updated and should work now (I installed via repo and examples in ?fit_zoidTMB work

**Comment by invertdna** [comment]
Yep, works!

The only hitch is in the third example. You’ve got `fit_zoid` as the function there, and you want `fit_zoidTMB`. If you run that random-effects example with `fit_zoidTMB`, it works, but you get the following warning:

`Warning message:`
`In Ops.factor(1, fac) : ‘|’ not meaningful for factors`

Not sure if we should care about that. But hooray!
